export const SiteRouter = {
  index: '/',
  login: '/login',
  signUp: '/signup',
  signUpSuccess: '/signup/success',
  search: '/search',
  performanceList: '/performances',
  community: '/community',
  mypage: '/mypage',
  mypageInfo: '/mypage/info',
  userEdit: '/mypage/info/edit',
  changePassword: '/mypage/password',
  findAccount: '/find-account',
  performances: (id: string | number) => `/performances/${id}`,
  communityPost: (id: string | number) => `/community/${id}`,
  communityEdit: (id: string | number) => `/community/edit/${id}`,
  communityCreate: '/community/edit',
  aiChat: '/ai-chat',
} as const
